apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backendwsock
  labels:
    name: backendwsock 
spec:
  rules:
    - host: archi-exemple-wsock-backend.kub.sspcloud.fr
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: backendwsock 
                port:
                  number: 80