apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wsock
  labels:
    name: wsock
spec:
  rules:
    - host: websocketclogwsock.kub.sspcloud.fr
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: wsock 
                port:
                  number: 80