apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-frontendwsock
data:
  VITE_API_URL: https://backend-conception-logicielle.kub.sspcloud.fr
  VITE_ENVIRONNEMENT: sspcloud-pd
  __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "frontend-conception-logicielle.kub.sspcloud.fr"