apiVersion: v1
kind: ConfigMap
metadata:
  name: configuration-frontendwsock
data:
  VITE_API_URL: https://backendclogwsock.kub.sspcloud.fr
  VITE_WS_URL: websocketclogwsock.kub.sspcloud.fr
  VITE_ENVIRONNEMENT: sspcloud-pd
  __VITE_ADDITIONAL_SERVER_ALLOWED_HOSTS: "frontendlogwsock.kub.sspcloud.fr"